--
-- Table Posts
--
DROP TABLE IF EXISTS Posts;
CREATE TABLE Posts (
    "id" INTEGER PRIMARY KEY NOT NULL,
    "content" TEXT NOT NULL,
    "date" DATETIME NOT NULL,
    "topic" INTEGER NOT NULL,
    "author" TEXT NOT NULL,
    "rank" INTEGER NOT NULL DEFAULT 0,
    "accepted" BOOLEAN NOT NULL DEFAULT false,
    FOREIGN KEY(topic) REFERENCES Topics(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(author) REFERENCES Users(username) ON DELETE RESTRICT ON UPDATE CASCADE
);
